### ISSUE TITLE
[BUG] Item image deleted

### ISSUE THREAD

**Issue by victorbillaud** [victorbillaud/tomato#95]
Fix this bug

https://github.com/victorbillaud/tomato/assets/61359041/6918e901-812b-405c-af4c-9ee4b54d969d

Also add a button delete photo.

**Comment by Arthur-PI** [comment]
Strange but ok, will do

**Comment by Arthur-PI** [comment]
@victorbillaud can't reproduce on my Macbook pro 16' M1 Pro 512Go 😢.
Its working just fine for me, try to do it again
